### ISSUE TITLE
Improve configuration managment

### ISSUE THREAD

**Issue by andreffs18** [checkr/pyflagr#4]
Looking at https://github.com/checkr/pyflagr/blob/master/flagr/configuration.py, we can see that this SDK was generated using Swagger Code Generation tool. 

It would be great to have the possibility to iterate this to allow custom configs, like different Host urls, which right now is set to only localhost.

Am I missing something or the only way to do that is by going to the ```host``` variable and replace it with what we need?

```python
from flagr import EvaluationApi, EvalContext
from flagr.rest import ApiException

api_instance = EvaluationApi()
# override configuration host to map our Flagr instance
api_instance.api_client.configuration.host = "https://MY_FLAGR_API_URL.com"

body = EvalContext(flag_key="feature_A", entity_context={"username": username})
response = api_instance.post_evaluation(body)
#  response.variant_key
```

Thanks

**Comment by ismaeIfm** [comment]
@andreffs18 That code is not meant to be modified like that. If you want to add custom configs you need to modify the content of [swagger.yaml](https://github.com/checkr/pyflagr/blob/master/swagger.yaml) and generate the `.py` files. For example, to change the host you need to add it in the `swagger.yaml` like this:
```yaml
host: https://MY_FLAGR_API_URL.com
```
and then execute a `make` in the root of the repo. Hope this helps.

**Comment by zhouzhuojie** [comment]
@andreffs18 I was looking through the code and see if there's any place other than the configuration that sets the base url.

https://github.com/checkr/pyflagr/blob/master/flagr/configuration.py#L50
https://github.com/checkr/pyflagr/blob/855737233856c71bf1c7b086b6e2cbc7c0ecef0d/flagr/api_client.py#L146

I think you're right, overriding `configuration.host = "https://MY_FLAGR_API_URL.com"` is probably the intended way of doing it in this generated client. I think in your application it just need a few lines to setup the api_client.

I don't think users need to `make gen` with the swagger.yaml, it adds some extra steps and you need to maintain the generated python client for your application.
