### ISSUE TITLE
How to setting the url path? Port number?

### ISSUE THREAD

**Issue by Ilfarro** [checkr/pyflagr#7]
How to change the relative url path from http://localhost/api/v1, into http://localhost:18000/api/v1 for example?

**Comment by arrase** [comment]
```
api_instance = flagr.EvaluationApi()
api_instance.api_client.configuration.host = <YOUR URL>
```

**Comment by zhouzhuojie** [comment]
Thanks, and the configuration code can be found here 
https://github.com/checkr/pyflagr/blob/master/flagr/configuration.py#L47
